minimum_pre_commit_version: 2.15.0
exclude: ^LICENSE*/|\.(html|csv|svg|mp4|webm|ogg)|Pipfile.lock$
default_stages: [commit, merge-commit, push, prepare-commit-msg, commit-msg, post-checkout, post-commit, post-merge, post-rewrite]
repos:
-   repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: \.txt$
        stages: [ commit, merge-commit, push, prepare-commit-msg, commit-msg, post-checkout, post-commit, post-merge, post-rewrite ]
    -   id: trailing-whitespace
        stages: [commit, merge-commit, push, prepare-commit-msg, commit-msg, post-checkout, post-commit, post-merge, post-rewrite]
    -   id: check-merge-conflict
    -   id: check-added-large-files
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: &flake8_dependencies
        - flake8==4.0.1
        - flake8-comprehensions==3.7.0
        - flake8-bugbear==21.3.2
        args: [--config, .flake8]
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
